[package]
name = "Scale"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SuiCoin = { local = "../coin" }
Oracle = { local = "../oracle" }
[addresses]
scale =  "0x0"
sui =  "0x2"
# oracle = "0x6185a80cb5bbc719105a7a9caf35399c1ffbd329"
# sui_coin = "0x3"