[package]
name = "SuiCoin"
version = "0.0.2"
published-at = "0x96d69a6e529949ea3a452f9705227860903b9085ba805808cb37a2f867883f64"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
# Sui = { local = "../../sui/crates/sui-framework/packages/sui-framework"}
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"
[addresses]
sui_coin =  "0x96d69a6e529949ea3a452f9705227860903b9085ba805808cb37a2f867883f64"
sui =  "0x2"