[package]
name = "SuiCoin"
version = "0.0.1"
published-at = "0x2312955c35acc8a73aef16cdf541b33fa027fe3cfba6a01d297c572449e9cdb5"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
Sui = { local = "../../sui/crates/sui-framework/packages/sui-framework"}

[addresses]
sui_coin =  "0x2312955c35acc8a73aef16cdf541b33fa027fe3cfba6a01d297c572449e9cdb5"
sui =  "0x2"