[package]
name = "SuiCoin"
version = "0.0.2"
published-at = "0x2101c92efa3e3a8720b77229a1f706d7011d8c5be1a97cf3d7fa732116f4a1ee"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
# Sui = { local = "../../sui/crates/sui-framework/packages/sui-framework"}
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"
[addresses]
sui_coin =  "0x0"
sui =  "0x2"